apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache-web
spec:
  containers:
  - name: apache-container
    image: httpd:alpine
    resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
    ports:
      - containerPort: 80
