apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      pod: grafana-pod
  template:
    metadata:
      labels:
        pod: grafana-pod
    spec:
      nodeSelector:
        grafana: running
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000