apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kbroletest1-rb
  namespace: web-apps
subjects: 
- kind: User
  name: kbroletest1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-service-reader
  apiGroup: rbac.authorization.k8s.io