apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: web-apps
spec:
  type: NodePort #type of service (Nodeport exposes service on your nodes)
  selector: #who is this service routing to
    pod: nginx #should match label of pod
  ports:
  - protocol: TCP
    port: 80 #port of the service
    targetPort: 80 #port of the pod
    nodePort: 31030 #range must be between 30000-32767

