apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
  namespace: web-apps
spec:
  type: ClusterIP #type of service (exposes ports internally on cluster)
  selector: #who is this service routing to
    pod: nginx #should match label of pod
  ports:
  - protocol: TCP
    port: 80 #port of the service
    targetPort: 80 #port of the pod

