apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: web
  labels:
    function: my-daemonset
spec:
  selector:
    matchLabels:
      pod: block-pod #which pod the daemonset will be managing
  template:
    metadata:
      labels:
        pod: block-pod #pod being managed
    spec:
      nodeSelector:
        test: passed
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        -  containerPort: 80
