apiVersion: v1
kind: Pod
metadata: 
  namespace: web
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
    - containerPort: 80
    