apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer-service
  namespace: web-apps
spec:
  type: LoadBalancer #type of service (creates an internet facing load balancer)
  selector: #who is this service routing to
    pod: prometheus #should match label of pod
  ports:
  - protocol: TCP
    port: 80 #port of the service
    targetPort: 9090 #port of the pod

