apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: cache
  labels:
    app: redis
spec:
  containers:
  - name: redis-container
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
