apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
  namespace: webns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: sc-web #must match the name of the storage class as defined in its file (storageclass.yaml)
